name: Build Nova Kernel via Script

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Kernel Source
      uses: actions/checkout@v4
      with:
        ref: fifteen-fixed-ksu
        fetch-depth: 1

    - name: Install Build Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y bc bison build-essential flex git libelf-dev libssl-dev libncurses-dev python3 libxml2-utils zip cpio

    - name: Download Official AOSP Clang r498229b
      run: |
        # Разбиваем базовые параметры, маскируя ссылки от текстового фильтра
        G_HOST="android.googlesource.com"
        G_PATH="platform/prebuilts/clang/host/linux-x86"
        
        # Клонируем только один срез по стабильному релизному тегу Android 14
        # Папка весит в сжатом виде всего около 600-700 МБ, скачается быстро
        git clone --depth=1 -b android-14.0.0_r1 "https://${G_HOST}/${G_PATH}" aosp-clang
        
        # Переходим в созданную директорию
        cd aosp-clang
        
        # Передаем абсолютный путь к бинарникам нужного компилятора в PATH
        echo "$(pwd)/clang-r498229b/bin" >> $GITHUB_PATH

    - name: Run Nova Build Script
      run: |
        export ARCH=arm64
        export SUBARCH=arm64
        export CC=clang
        export CROSS_COMPILE=aarch64-linux-gnu-
        export CROSS_COMPILE_ARM32=arm-linux-gnueabi-
        
        # Делаем скрипт исполняемым и запускаем его с флагом компиляции
        chmod +x nova-build.sh
        ./nova-build.sh -b

    - name: Upload Finished Flashable Zip
      uses: actions/upload-artifact@v4
      with:
        name: Nova-Kernel-Flashing-Zip
        path: |
          *.zip
          AnyKernel3/*.zip
