name: Build Kernel on GitHub Actions

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout source
      uses: actions/checkout@v3
      with: 
        submodules: recursive

    - name: Update Environment
      run: #sudo apt update -y && sudo apt upgrade -y

    - name: Install Dependencies
      run: |
        #sudo apt install -y git-core gnupg flex bc bison build-essential zip \
        curl zlib1g-dev g++-multilib libc6-dev-i386 lib32ncurses5-dev \
        xsltproc unzip python2 python3 python3-pip python3-dev \
        python-is-python3 schedtool ccache libtinfo5 libncurses5 lzop tmux \
        patchelf git-lfs ripgrep clang-11

    - name: Download Neutron Toolchain
      run: bash build.sh --tools

    - name: Build Nova
      run: bash build.sh --build

    - name: Upload Finished Flashable Zip
      uses: actions/upload-artifact@v4
      with:
        name: Nova-Kernel-Flashing-Zip
        path: |
          *.zip
          AnyKernel3/*.zip

    - name: Prepare and Upload Kernel Headers Kit
      run: |
        # Создаем папку для сохранения среды разработки драйверов/модулей
        mkdir -p kernel-dev-kit
        
        # Копируем сгенерированные файлы символов функций и текущий рабочий конфиг
        cp System.map Module.symvers .config kernel-dev-kit/ 2>/dev/null || true
        
        # Копируем структуру заголовочных файлов и бинарных скриптов сборщика
        cp -r --parents include/ kernel-dev-kit/ 2>/dev/null || true
        cp -r --parents arch/arm64/include/ kernel-dev-kit/ 2>/dev/null || true
        cp -r --parents scripts/ kernel-dev-kit/ 2>/dev/null || true
        
        # Запаковываем всё в компактный ZIP-архив
        zip -r Nova-Kernel-Headers.zip kernel-dev-kit/

    - name: Upload Kernel Headers Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Nova-Kernel-Development-Headers
        path: Nova-Kernel-Headers.zip
